### ISSUE TITLE
Temperatur support on MX480

### ISSUE THREAD

**Issue by sjurtf** [gathering/gondul#222]
r1.tele (MX480) rapporterer ikke temperatur i https://gondul.tg23.gathering.org/api/public/switch-state og vises heller ikke i kartet.

**Comment by KristianLyng** [comment]
Jeg har fått tak i en SKOG av SNMP-oider for MXer jeg skal se på, og fikse. Det er litt vrient siden den har ørt-og-ørti sensorer så hva som er "den ene riktige" er litt vrient å si, men vi skal i det minste forbedre. Vi bør også ha _alle_ sensorene tydelig i grafana uansett.

**Comment by sjurtf** [comment]
Ble fikset på TG23
